name: CI/CD - Simple Static Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # DevSecOps Skill: Static Code Analysis (Linting HTML)
      - name: Lint HTML
        run: |
          npm install html-validate
          ./node_modules/.bin/html-validate index.html
      
      # DevOps Skill: Trigger Render Deployment
      - name: Trigger Render Deployment
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl --request POST --header "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          --header "Content-Type: application/json" \
          --data '{"serviceId": "srv-d32frtjipnbc73d5dcug"}' \
          https://api.render.com/v1/deploys